/*
 * This file is generated by jOOQ.
 */
package com.novemb.jooq.model;


import com.novemb.jooq.model.tables.Job;
import com.novemb.jooq.model.tables.Location;
import com.novemb.jooq.model.tables.Status;
import com.novemb.jooq.model.tables.StatusType;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jobs</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index JOB_JOB_LOCATION_NAME_FK = Indexes0.JOB_JOB_LOCATION_NAME_FK;
    public static final Index JOB_PRIMARY = Indexes0.JOB_PRIMARY;
    public static final Index LOCATION_PRIMARY = Indexes0.LOCATION_PRIMARY;
    public static final Index STATUS_JOB_ID = Indexes0.STATUS_JOB_ID;
    public static final Index STATUS_PRIMARY = Indexes0.STATUS_PRIMARY;
    public static final Index STATUS_TYPE = Indexes0.STATUS_TYPE;
    public static final Index STATUS_TYPE_PRIMARY = Indexes0.STATUS_TYPE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index JOB_JOB_LOCATION_NAME_FK = Internal.createIndex("job_location_name_fk", Job.JOB, new OrderField[] { Job.JOB.LOCATION_NAME }, false);
        public static Index JOB_PRIMARY = Internal.createIndex("PRIMARY", Job.JOB, new OrderField[] { Job.JOB.ID }, true);
        public static Index LOCATION_PRIMARY = Internal.createIndex("PRIMARY", Location.LOCATION, new OrderField[] { Location.LOCATION.LOCATION_NAME }, true);
        public static Index STATUS_JOB_ID = Internal.createIndex("job_id", Status.STATUS, new OrderField[] { Status.STATUS.JOB_ID }, false);
        public static Index STATUS_PRIMARY = Internal.createIndex("PRIMARY", Status.STATUS, new OrderField[] { Status.STATUS.STATUS_ID }, true);
        public static Index STATUS_TYPE = Internal.createIndex("type", Status.STATUS, new OrderField[] { Status.STATUS.TYPE }, false);
        public static Index STATUS_TYPE_PRIMARY = Internal.createIndex("PRIMARY", StatusType.STATUS_TYPE, new OrderField[] { StatusType.STATUS_TYPE.STATUS_TYPE_ID }, true);
    }
}
