/*
 * This file is generated by jOOQ.
 */
package novemb.jooq.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import novemb.jooq.model.tables.Job;
import novemb.jooq.model.tables.Location;
import novemb.jooq.model.tables.Status;
import novemb.jooq.model.tables.StatusType;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jobs extends SchemaImpl {

    private static final long serialVersionUID = -870382398;

    /**
     * The reference instance of <code>jobs</code>
     */
    public static final Jobs JOBS = new Jobs();

    /**
     * The table <code>jobs.job</code>.
     */
    public final Job JOB = novemb.jooq.model.tables.Job.JOB;

    /**
     * The table <code>jobs.location</code>.
     */
    public final Location LOCATION = novemb.jooq.model.tables.Location.LOCATION;

    /**
     * The table <code>jobs.status</code>.
     */
    public final Status STATUS = novemb.jooq.model.tables.Status.STATUS;

    /**
     * The table <code>jobs.status_type</code>.
     */
    public final StatusType STATUS_TYPE = novemb.jooq.model.tables.StatusType.STATUS_TYPE;

    /**
     * No further instances allowed
     */
    private Jobs() {
        super("jobs", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return novemb.jooq.model.DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Job.JOB,
            Location.LOCATION,
            Status.STATUS,
            StatusType.STATUS_TYPE);
    }
}
