/*
 * This file is generated by jOOQ.
 */
package com.novemb.jooq.model;


import com.novemb.jooq.model.tables.Job;
import com.novemb.jooq.model.tables.Location;
import com.novemb.jooq.model.tables.Status;
import com.novemb.jooq.model.tables.StatusType;
import com.novemb.jooq.model.tables.records.JobRecord;
import com.novemb.jooq.model.tables.records.LocationRecord;
import com.novemb.jooq.model.tables.records.StatusRecord;
import com.novemb.jooq.model.tables.records.StatusTypeRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jobs</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<JobRecord, UInteger> IDENTITY_JOB = Identities0.IDENTITY_JOB;
    public static final Identity<StatusRecord, UInteger> IDENTITY_STATUS = Identities0.IDENTITY_STATUS;
    public static final Identity<StatusTypeRecord, UInteger> IDENTITY_STATUS_TYPE = Identities0.IDENTITY_STATUS_TYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JobRecord> KEY_JOB_PRIMARY = UniqueKeys0.KEY_JOB_PRIMARY;
    public static final UniqueKey<LocationRecord> KEY_LOCATION_PRIMARY = UniqueKeys0.KEY_LOCATION_PRIMARY;
    public static final UniqueKey<StatusRecord> KEY_STATUS_PRIMARY = UniqueKeys0.KEY_STATUS_PRIMARY;
    public static final UniqueKey<StatusTypeRecord> KEY_STATUS_TYPE_PRIMARY = UniqueKeys0.KEY_STATUS_TYPE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<JobRecord, LocationRecord> JOB_LOCATION_NAME_FK = ForeignKeys0.JOB_LOCATION_NAME_FK;
    public static final ForeignKey<StatusRecord, JobRecord> STATUS_IBFK_3 = ForeignKeys0.STATUS_IBFK_3;
    public static final ForeignKey<StatusRecord, StatusTypeRecord> STATUS_IBFK_1 = ForeignKeys0.STATUS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<JobRecord, UInteger> IDENTITY_JOB = Internal.createIdentity(Job.JOB, Job.JOB.ID);
        public static Identity<StatusRecord, UInteger> IDENTITY_STATUS = Internal.createIdentity(Status.STATUS, Status.STATUS.STATUS_ID);
        public static Identity<StatusTypeRecord, UInteger> IDENTITY_STATUS_TYPE = Internal.createIdentity(StatusType.STATUS_TYPE, StatusType.STATUS_TYPE.STATUS_TYPE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<JobRecord> KEY_JOB_PRIMARY = Internal.createUniqueKey(Job.JOB, "KEY_job_PRIMARY", Job.JOB.ID);
        public static final UniqueKey<LocationRecord> KEY_LOCATION_PRIMARY = Internal.createUniqueKey(Location.LOCATION, "KEY_location_PRIMARY", Location.LOCATION.LOCATION_NAME);
        public static final UniqueKey<StatusRecord> KEY_STATUS_PRIMARY = Internal.createUniqueKey(Status.STATUS, "KEY_status_PRIMARY", Status.STATUS.STATUS_ID);
        public static final UniqueKey<StatusTypeRecord> KEY_STATUS_TYPE_PRIMARY = Internal.createUniqueKey(StatusType.STATUS_TYPE, "KEY_status_type_PRIMARY", StatusType.STATUS_TYPE.STATUS_TYPE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<JobRecord, LocationRecord> JOB_LOCATION_NAME_FK = Internal.createForeignKey(com.novemb.jooq.model.Keys.KEY_LOCATION_PRIMARY, Job.JOB, "job_location_name_fk", Job.JOB.LOCATION_NAME);
        public static final ForeignKey<StatusRecord, JobRecord> STATUS_IBFK_3 = Internal.createForeignKey(com.novemb.jooq.model.Keys.KEY_JOB_PRIMARY, Status.STATUS, "status_ibfk_3", Status.STATUS.JOB_ID);
        public static final ForeignKey<StatusRecord, StatusTypeRecord> STATUS_IBFK_1 = Internal.createForeignKey(com.novemb.jooq.model.Keys.KEY_STATUS_TYPE_PRIMARY, Status.STATUS, "status_ibfk_1", Status.STATUS.TYPE);
    }
}
