/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model;


import com.march.jooq.model.routines.AddContinuance;
import com.march.jooq.model.routines.Kotoba;
import com.march.jooq.model.routines.TranslateToFakese;
import com.march.jooq.model.routines.TranslateToNoves;
import com.march.jooq.model.routines.WordAdd;

import javax.annotation.Generated;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in lexicon
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>lexicon.add_continuance</code>
     */
    public static void addContinuance(Configuration configuration, String item) {
        AddContinuance p = new AddContinuance();
        p.setItem(item);

        p.execute(configuration);
    }

    /**
     * Call <code>lexicon.kotoba</code>
     */
    public static void kotoba(Configuration configuration, String oneWord) {
        Kotoba p = new Kotoba();
        p.setOneWord(oneWord);

        p.execute(configuration);
    }

    /**
     * Call <code>lexicon.translate_to_fakese</code>
     */
    public static void translateToFakese(Configuration configuration, String originWord, String fakeseWord) {
        TranslateToFakese p = new TranslateToFakese();
        p.setOriginWord(originWord);
        p.setFakeseWord(fakeseWord);

        p.execute(configuration);
    }

    /**
     * Call <code>lexicon.translate_to_noves</code>
     */
    public static void translateToNoves(Configuration configuration, String originWord, String novesWord) {
        TranslateToNoves p = new TranslateToNoves();
        p.setOriginWord(originWord);
        p.setNovesWord(novesWord);

        p.execute(configuration);
    }

    /**
     * Call <code>lexicon.word_add</code>
     */
    public static void wordAdd(Configuration configuration, String item) {
        WordAdd p = new WordAdd();
        p.setItem(item);

        p.execute(configuration);
    }
}
