/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model;


import com.march.jooq.model.tables.Docs;
import com.march.jooq.model.tables.Langs;
import com.march.jooq.model.tables.Textstring;
import com.march.jooq.model.tables.Translations;
import com.march.jooq.model.tables.Words;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>lexicon</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DOCS_DOC_REV = Indexes0.DOCS_DOC_REV;
    public static final Index DOCS_PRIMARY = Indexes0.DOCS_PRIMARY;
    public static final Index LANGS_LANG_NAME = Indexes0.LANGS_LANG_NAME;
    public static final Index LANGS_PRIMARY = Indexes0.LANGS_PRIMARY;
    public static final Index TEXTSTRING_DOC_TEXTSTRING_FK = Indexes0.TEXTSTRING_DOC_TEXTSTRING_FK;
    public static final Index TEXTSTRING_PRIMARY = Indexes0.TEXTSTRING_PRIMARY;
    public static final Index TEXTSTRING_WORD_TEXTSTRING_FK = Indexes0.TEXTSTRING_WORD_TEXTSTRING_FK;
    public static final Index TRANSLATIONS_FROM_WORD_TRANS_FK = Indexes0.TRANSLATIONS_FROM_WORD_TRANS_FK;
    public static final Index TRANSLATIONS_PRIMARY = Indexes0.TRANSLATIONS_PRIMARY;
    public static final Index TRANSLATIONS_TO_LANG_TRANS_FK = Indexes0.TRANSLATIONS_TO_LANG_TRANS_FK;
    public static final Index WORDS_PRIMARY = Indexes0.WORDS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DOCS_DOC_REV = Internal.createIndex("doc_rev", Docs.DOCS, new OrderField[] { Docs.DOCS.DOC_NAME, Docs.DOCS.REVISION }, true);
        public static Index DOCS_PRIMARY = Internal.createIndex("PRIMARY", Docs.DOCS, new OrderField[] { Docs.DOCS.DOC_ID }, true);
        public static Index LANGS_LANG_NAME = Internal.createIndex("lang_name", Langs.LANGS, new OrderField[] { Langs.LANGS.LANG_NAME }, true);
        public static Index LANGS_PRIMARY = Internal.createIndex("PRIMARY", Langs.LANGS, new OrderField[] { Langs.LANGS.LANG_ID }, true);
        public static Index TEXTSTRING_DOC_TEXTSTRING_FK = Internal.createIndex("doc_textstring_fk", Textstring.TEXTSTRING, new OrderField[] { Textstring.TEXTSTRING.DOC_ID }, false);
        public static Index TEXTSTRING_PRIMARY = Internal.createIndex("PRIMARY", Textstring.TEXTSTRING, new OrderField[] { Textstring.TEXTSTRING.WORD_ID }, true);
        public static Index TEXTSTRING_WORD_TEXTSTRING_FK = Internal.createIndex("word_textstring_fk", Textstring.TEXTSTRING, new OrderField[] { Textstring.TEXTSTRING.WORD }, false);
        public static Index TRANSLATIONS_FROM_WORD_TRANS_FK = Internal.createIndex("from_word_trans_fk", Translations.TRANSLATIONS, new OrderField[] { Translations.TRANSLATIONS.FROM_WORD }, false);
        public static Index TRANSLATIONS_PRIMARY = Internal.createIndex("PRIMARY", Translations.TRANSLATIONS, new OrderField[] { Translations.TRANSLATIONS.TRANS_ID }, true);
        public static Index TRANSLATIONS_TO_LANG_TRANS_FK = Internal.createIndex("to_lang_trans_fk", Translations.TRANSLATIONS, new OrderField[] { Translations.TRANSLATIONS.TO_LANG }, false);
        public static Index WORDS_PRIMARY = Internal.createIndex("PRIMARY", Words.WORDS, new OrderField[] { Words.WORDS.WORD }, true);
    }
}
