/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model;


import com.march.jooq.model.tables.Docs;
import com.march.jooq.model.tables.Langs;
import com.march.jooq.model.tables.Textstring;
import com.march.jooq.model.tables.Translations;
import com.march.jooq.model.tables.Words;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in lexicon
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>lexicon.docs</code>.
     */
    public static final Docs DOCS = com.march.jooq.model.tables.Docs.DOCS;

    /**
     * The table <code>lexicon.langs</code>.
     */
    public static final Langs LANGS = com.march.jooq.model.tables.Langs.LANGS;

    /**
     * The table <code>lexicon.textstring</code>.
     */
    public static final Textstring TEXTSTRING = com.march.jooq.model.tables.Textstring.TEXTSTRING;

    /**
     * The table <code>lexicon.translations</code>.
     */
    public static final Translations TRANSLATIONS = com.march.jooq.model.tables.Translations.TRANSLATIONS;

    /**
     * The table <code>lexicon.words</code>.
     */
    public static final Words WORDS = com.march.jooq.model.tables.Words.WORDS;
}
