/*
 * This file is generated by jOOQ.
 */
package novemb.jooq.model.tables.records;


import javax.annotation.Generated;

import novemb.jooq.model.tables.Location;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationRecord extends UpdatableRecordImpl<LocationRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1191508109;

    /**
     * Setter for <code>jobs.location.location_name</code>.
     */
    public void setLocationName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobs.location.location_name</code>.
     */
    public String getLocationName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jobs.location.region</code>.
     */
    public void setRegion(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobs.location.region</code>.
     */
    public String getRegion() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Location.LOCATION.LOCATION_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Location.LOCATION.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getLocationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getLocationName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord value1(String value) {
        setLocationName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord value2(String value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocationRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationRecord
     */
    public LocationRecord() {
        super(Location.LOCATION);
    }

    /**
     * Create a detached, initialised LocationRecord
     */
    public LocationRecord(String locationName, String region) {
        super(Location.LOCATION);

        set(0, locationName);
        set(1, region);
    }
}
