/*
 * This file is generated by jOOQ.
 */
package com.novemb.jooq.model.tables.records;


import com.novemb.jooq.model.tables.StatusType;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusTypeRecord extends UpdatableRecordImpl<StatusTypeRecord> implements Record3<UInteger, String, String> {

    private static final long serialVersionUID = 724415795;

    /**
     * Setter for <code>jobs.status_type.status_type_id</code>.
     */
    public void setStatusTypeId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobs.status_type.status_type_id</code>.
     */
    public UInteger getStatusTypeId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>jobs.status_type.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobs.status_type.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jobs.status_type.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobs.status_type.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return StatusType.STATUS_TYPE.STATUS_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StatusType.STATUS_TYPE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StatusType.STATUS_TYPE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getStatusTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getStatusTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusTypeRecord value1(UInteger value) {
        setStatusTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusTypeRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusTypeRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusTypeRecord values(UInteger value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusTypeRecord
     */
    public StatusTypeRecord() {
        super(StatusType.STATUS_TYPE);
    }

    /**
     * Create a detached, initialised StatusTypeRecord
     */
    public StatusTypeRecord(UInteger statusTypeId, String name, String description) {
        super(StatusType.STATUS_TYPE);

        set(0, statusTypeId);
        set(1, name);
        set(2, description);
    }
}
