/*
 * This file is generated by jOOQ.
 */
package com.novemb.jooq.model.tables.records;


import com.novemb.jooq.model.tables.Status;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusRecord extends UpdatableRecordImpl<StatusRecord> implements Record5<UInteger, UInteger, UInteger, Timestamp, String> {

    private static final long serialVersionUID = -3361467;

    /**
     * Setter for <code>jobs.status.status_id</code>.
     */
    public void setStatusId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>jobs.status.status_id</code>.
     */
    public UInteger getStatusId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>jobs.status.job_id</code>.
     */
    public void setJobId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>jobs.status.job_id</code>.
     */
    public UInteger getJobId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>jobs.status.type</code>.
     */
    public void setType(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>jobs.status.type</code>.
     */
    public UInteger getType() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>jobs.status.as_of</code>.
     */
    public void setAsOf(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>jobs.status.as_of</code>.
     */
    public Timestamp getAsOf() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>jobs.status.notes</code>.
     */
    public void setNotes(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jobs.status.notes</code>.
     */
    public String getNotes() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UInteger, Timestamp, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, UInteger, Timestamp, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Status.STATUS.STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Status.STATUS.JOB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return Status.STATUS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Status.STATUS.AS_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Status.STATUS.NOTES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getAsOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getJobId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getAsOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNotes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusRecord value1(UInteger value) {
        setStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusRecord value2(UInteger value) {
        setJobId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusRecord value3(UInteger value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusRecord value4(Timestamp value) {
        setAsOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusRecord value5(String value) {
        setNotes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatusRecord values(UInteger value1, UInteger value2, UInteger value3, Timestamp value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusRecord
     */
    public StatusRecord() {
        super(Status.STATUS);
    }

    /**
     * Create a detached, initialised StatusRecord
     */
    public StatusRecord(UInteger statusId, UInteger jobId, UInteger type, Timestamp asOf, String notes) {
        super(Status.STATUS);

        set(0, statusId);
        set(1, jobId);
        set(2, type);
        set(3, asOf);
        set(4, notes);
    }
}
