/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model.routines;


import com.march.jooq.model.Lexicon;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RevDocAdd extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1623569646;

    /**
     * The parameter <code>lexicon.rev_doc_add.new_doc</code>.
     */
    public static final Parameter<String> NEW_DOC = createParameter("new_doc", org.jooq.impl.SQLDataType.VARCHAR(256), false, false);

    /**
     * The parameter <code>lexicon.rev_doc_add.rev</code>.
     */
    public static final Parameter<Long> REV = createParameter("rev", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public RevDocAdd() {
        super("rev_doc_add", Lexicon.LEXICON);

        addInParameter(NEW_DOC);
        addInParameter(REV);
    }

    /**
     * Set the <code>new_doc</code> parameter IN value to the routine
     */
    public void setNewDoc(String value) {
        setValue(NEW_DOC, value);
    }

    /**
     * Set the <code>rev</code> parameter IN value to the routine
     */
    public void setRev(Long value) {
        setValue(REV, value);
    }
}
