/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model.routines;


import com.march.jooq.model.Lexicon;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WordAdd extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -656935866;

    /**
     * The parameter <code>lexicon.word_add.item</code>.
     */
    public static final Parameter<String> ITEM = createParameter("item", org.jooq.impl.SQLDataType.VARCHAR(100), false, false);

    /**
     * Create a new routine call instance
     */
    public WordAdd() {
        super("word_add", Lexicon.LEXICON);

        addInParameter(ITEM);
    }

    /**
     * Set the <code>item</code> parameter IN value to the routine
     */
    public void setItem(String value) {
        setValue(ITEM, value);
    }
}
