/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model.tables.records;


import com.march.jooq.model.tables.Langs;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangsRecord extends UpdatableRecordImpl<LangsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1549763007;

    /**
     * Setter for <code>lexicon.langs.lang_id</code>.
     */
    public void setLangId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lexicon.langs.lang_id</code>.
     */
    public Integer getLangId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lexicon.langs.lang_name</code>.
     */
    public void setLangName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lexicon.langs.lang_name</code>.
     */
    public String getLangName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Langs.LANGS.LANG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Langs.LANGS.LANG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLangName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLangId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLangName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangsRecord value1(Integer value) {
        setLangId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangsRecord value2(String value) {
        setLangName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangsRecord
     */
    public LangsRecord() {
        super(Langs.LANGS);
    }

    /**
     * Create a detached, initialised LangsRecord
     */
    public LangsRecord(Integer langId, String langName) {
        super(Langs.LANGS);

        set(0, langId);
        set(1, langName);
    }
}
