/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model.tables.records;


import com.march.jooq.model.tables.Textstring;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextstringRecord extends UpdatableRecordImpl<TextstringRecord> implements Record6<Integer, String, Integer, Timestamp, Byte, Byte> {

    private static final long serialVersionUID = -1079687901;

    /**
     * Setter for <code>lexicon.textstring.word_id</code>.
     */
    public void setWordId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lexicon.textstring.word_id</code>.
     */
    public Integer getWordId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lexicon.textstring.word</code>.
     */
    public void setWord(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lexicon.textstring.word</code>.
     */
    public String getWord() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lexicon.textstring.doc_id</code>.
     */
    public void setDocId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>lexicon.textstring.doc_id</code>.
     */
    public Integer getDocId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>lexicon.textstring.tstamp</code>.
     */
    public void setTstamp(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>lexicon.textstring.tstamp</code>.
     */
    public Timestamp getTstamp() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>lexicon.textstring.left_continuance</code>.
     */
    public void setLeftContinuance(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>lexicon.textstring.left_continuance</code>.
     */
    public Byte getLeftContinuance() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>lexicon.textstring.right_continuance</code>.
     */
    public void setRightContinuance(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>lexicon.textstring.right_continuance</code>.
     */
    public Byte getRightContinuance() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Timestamp, Byte, Byte> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Timestamp, Byte, Byte> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Textstring.TEXTSTRING.WORD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Textstring.TEXTSTRING.WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Textstring.TEXTSTRING.DOC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Textstring.TEXTSTRING.TSTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Textstring.TEXTSTRING.LEFT_CONTINUANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Textstring.TEXTSTRING.RIGHT_CONTINUANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDocId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTstamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getLeftContinuance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getRightContinuance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWordId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDocId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTstamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getLeftContinuance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getRightContinuance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord value1(Integer value) {
        setWordId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord value2(String value) {
        setWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord value3(Integer value) {
        setDocId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord value4(Timestamp value) {
        setTstamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord value5(Byte value) {
        setLeftContinuance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord value6(Byte value) {
        setRightContinuance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TextstringRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Byte value5, Byte value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TextstringRecord
     */
    public TextstringRecord() {
        super(Textstring.TEXTSTRING);
    }

    /**
     * Create a detached, initialised TextstringRecord
     */
    public TextstringRecord(Integer wordId, String word, Integer docId, Timestamp tstamp, Byte leftContinuance, Byte rightContinuance) {
        super(Textstring.TEXTSTRING);

        set(0, wordId);
        set(1, word);
        set(2, docId);
        set(3, tstamp);
        set(4, leftContinuance);
        set(5, rightContinuance);
    }
}
