/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model.tables.records;


import com.march.jooq.model.tables.Translations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TranslationsRecord extends UpdatableRecordImpl<TranslationsRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 1108921860;

    /**
     * Setter for <code>lexicon.translations.trans_id</code>.
     */
    public void setTransId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>lexicon.translations.trans_id</code>.
     */
    public Integer getTransId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>lexicon.translations.trans</code>.
     */
    public void setTrans(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lexicon.translations.trans</code>.
     */
    public String getTrans() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lexicon.translations.from_word</code>.
     */
    public void setFromWord(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lexicon.translations.from_word</code>.
     */
    public String getFromWord() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lexicon.translations.to_lang</code>.
     */
    public void setToLang(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>lexicon.translations.to_lang</code>.
     */
    public Integer getToLang() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Translations.TRANSLATIONS.TRANS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Translations.TRANSLATIONS.TRANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Translations.TRANSLATIONS.FROM_WORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Translations.TRANSLATIONS.TO_LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getTransId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTrans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getFromWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getToLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTransId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTrans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFromWord();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getToLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranslationsRecord value1(Integer value) {
        setTransId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranslationsRecord value2(String value) {
        setTrans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranslationsRecord value3(String value) {
        setFromWord(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranslationsRecord value4(Integer value) {
        setToLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TranslationsRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TranslationsRecord
     */
    public TranslationsRecord() {
        super(Translations.TRANSLATIONS);
    }

    /**
     * Create a detached, initialised TranslationsRecord
     */
    public TranslationsRecord(Integer transId, String trans, String fromWord, Integer toLang) {
        super(Translations.TRANSLATIONS);

        set(0, transId);
        set(1, trans);
        set(2, fromWord);
        set(3, toLang);
    }
}
