/*
 * This file is generated by jOOQ.
 */
package com.march.jooq.model.tables;


import com.march.jooq.model.Indexes;
import com.march.jooq.model.Keys;
import com.march.jooq.model.Lexicon;
import com.march.jooq.model.tables.records.DocsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Docs extends TableImpl<DocsRecord> {

    private static final long serialVersionUID = 404904541;

    /**
     * The reference instance of <code>lexicon.docs</code>
     */
    public static final Docs DOCS = new Docs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocsRecord> getRecordType() {
        return DocsRecord.class;
    }

    /**
     * The column <code>lexicon.docs.doc_id</code>.
     */
    public final TableField<DocsRecord, Integer> DOC_ID = createField("doc_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>lexicon.docs.doc_name</code>.
     */
    public final TableField<DocsRecord, String> DOC_NAME = createField("doc_name", org.jooq.impl.SQLDataType.VARCHAR(256), this, "");

    /**
     * The column <code>lexicon.docs.sightings</code>.
     */
    public final TableField<DocsRecord, Integer> SIGHTINGS = createField("sightings", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>lexicon.docs</code> table reference
     */
    public Docs() {
        this(DSL.name("docs"), null);
    }

    /**
     * Create an aliased <code>lexicon.docs</code> table reference
     */
    public Docs(String alias) {
        this(DSL.name(alias), DOCS);
    }

    /**
     * Create an aliased <code>lexicon.docs</code> table reference
     */
    public Docs(Name alias) {
        this(alias, DOCS);
    }

    private Docs(Name alias, Table<DocsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Docs(Name alias, Table<DocsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Docs(Table<O> child, ForeignKey<O, DocsRecord> key) {
        super(child, key, DOCS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lexicon.LEXICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DOCS_DOC_NAME, Indexes.DOCS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DocsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DOCS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DocsRecord> getPrimaryKey() {
        return Keys.KEY_DOCS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DocsRecord>> getKeys() {
        return Arrays.<UniqueKey<DocsRecord>>asList(Keys.KEY_DOCS_PRIMARY, Keys.KEY_DOCS_DOC_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Docs as(String alias) {
        return new Docs(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Docs as(Name alias) {
        return new Docs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Docs rename(String name) {
        return new Docs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Docs rename(Name name) {
        return new Docs(name, null);
    }
}
